//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace TRMWebTestRig.net.webservicex.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UKLocationSoap", Namespace="http://www.webserviceX.NET")]
    public partial class UKLocation : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUKLocationByCountyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUKLocationByTownOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUKLocationByPostCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateUKAddressOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UKLocation() {
            this.Url = global::TRMWebTestRig.Properties.Settings.Default.TRMWebTestRig_net_webservicex_www_UKLocation;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUKLocationByCountyCompletedEventHandler GetUKLocationByCountyCompleted;
        
        /// <remarks/>
        public event GetUKLocationByTownCompletedEventHandler GetUKLocationByTownCompleted;
        
        /// <remarks/>
        public event GetUKLocationByPostCodeCompletedEventHandler GetUKLocationByPostCodeCompleted;
        
        /// <remarks/>
        public event ValidateUKAddressCompletedEventHandler ValidateUKAddressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/GetUKLocationByCounty", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUKLocationByCounty(string County) {
            object[] results = this.Invoke("GetUKLocationByCounty", new object[] {
                        County});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUKLocationByCountyAsync(string County) {
            this.GetUKLocationByCountyAsync(County, null);
        }
        
        /// <remarks/>
        public void GetUKLocationByCountyAsync(string County, object userState) {
            if ((this.GetUKLocationByCountyOperationCompleted == null)) {
                this.GetUKLocationByCountyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUKLocationByCountyOperationCompleted);
            }
            this.InvokeAsync("GetUKLocationByCounty", new object[] {
                        County}, this.GetUKLocationByCountyOperationCompleted, userState);
        }
        
        private void OnGetUKLocationByCountyOperationCompleted(object arg) {
            if ((this.GetUKLocationByCountyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUKLocationByCountyCompleted(this, new GetUKLocationByCountyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/GetUKLocationByTown", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUKLocationByTown(string Town) {
            object[] results = this.Invoke("GetUKLocationByTown", new object[] {
                        Town});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUKLocationByTownAsync(string Town) {
            this.GetUKLocationByTownAsync(Town, null);
        }
        
        /// <remarks/>
        public void GetUKLocationByTownAsync(string Town, object userState) {
            if ((this.GetUKLocationByTownOperationCompleted == null)) {
                this.GetUKLocationByTownOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUKLocationByTownOperationCompleted);
            }
            this.InvokeAsync("GetUKLocationByTown", new object[] {
                        Town}, this.GetUKLocationByTownOperationCompleted, userState);
        }
        
        private void OnGetUKLocationByTownOperationCompleted(object arg) {
            if ((this.GetUKLocationByTownCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUKLocationByTownCompleted(this, new GetUKLocationByTownCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/GetUKLocationByPostCode", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUKLocationByPostCode(string PostCode) {
            object[] results = this.Invoke("GetUKLocationByPostCode", new object[] {
                        PostCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUKLocationByPostCodeAsync(string PostCode) {
            this.GetUKLocationByPostCodeAsync(PostCode, null);
        }
        
        /// <remarks/>
        public void GetUKLocationByPostCodeAsync(string PostCode, object userState) {
            if ((this.GetUKLocationByPostCodeOperationCompleted == null)) {
                this.GetUKLocationByPostCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUKLocationByPostCodeOperationCompleted);
            }
            this.InvokeAsync("GetUKLocationByPostCode", new object[] {
                        PostCode}, this.GetUKLocationByPostCodeOperationCompleted, userState);
        }
        
        private void OnGetUKLocationByPostCodeOperationCompleted(object arg) {
            if ((this.GetUKLocationByPostCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUKLocationByPostCodeCompleted(this, new GetUKLocationByPostCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.webserviceX.NET/ValidateUKAddress", RequestNamespace="http://www.webserviceX.NET", ResponseNamespace="http://www.webserviceX.NET", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateUKAddress(string Town, string County, string PostCode) {
            object[] results = this.Invoke("ValidateUKAddress", new object[] {
                        Town,
                        County,
                        PostCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUKAddressAsync(string Town, string County, string PostCode) {
            this.ValidateUKAddressAsync(Town, County, PostCode, null);
        }
        
        /// <remarks/>
        public void ValidateUKAddressAsync(string Town, string County, string PostCode, object userState) {
            if ((this.ValidateUKAddressOperationCompleted == null)) {
                this.ValidateUKAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUKAddressOperationCompleted);
            }
            this.InvokeAsync("ValidateUKAddress", new object[] {
                        Town,
                        County,
                        PostCode}, this.ValidateUKAddressOperationCompleted, userState);
        }
        
        private void OnValidateUKAddressOperationCompleted(object arg) {
            if ((this.ValidateUKAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUKAddressCompleted(this, new ValidateUKAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUKLocationByCountyCompletedEventHandler(object sender, GetUKLocationByCountyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUKLocationByCountyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUKLocationByCountyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUKLocationByTownCompletedEventHandler(object sender, GetUKLocationByTownCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUKLocationByTownCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUKLocationByTownCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GetUKLocationByPostCodeCompletedEventHandler(object sender, GetUKLocationByPostCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUKLocationByPostCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUKLocationByPostCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ValidateUKAddressCompletedEventHandler(object sender, ValidateUKAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUKAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUKAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591